
export const POST_STUDENT= "POST_STUDENT"

export const PUT_STUDENT= "PUT_STUDENT"

export const GET_ALL_STUDENT= "GET_ALL_STUDENT"

export const DELETE_STUDENT= "DELETE_STUDENT"

export const SET_STUDENT = "SET_STUDENT"